#ifndef ATARI_KEYS_H
#define ATARI_KEYS_H

#define ATARI_SCANCODE_ESCAPE      0x01
#define ATARI_SCANCODE_1           0x02
#define ATARI_SCANCODE_2           0x03
#define ATARI_SCANCODE_3           0x04
#define ATARI_SCANCODE_4           0x05
#define ATARI_SCANCODE_5           0x06
#define ATARI_SCANCODE_6           0x07
#define ATARI_SCANCODE_7           0x08
#define ATARI_SCANCODE_8           0x09
#define ATARI_SCANCODE_9           0x0a
#define ATARI_SCANCODE_0           0x0b
#define ATARI_SCANCODE_MINUS       0x0c
#define ATARI_SCANCODE_EQUALS      0x0d
#define ATARI_SCANCODE_BACKSPACE   0x0e
#define ATARI_SCANCODE_TAB         0x0f
#define ATARI_SCANCODE_Q           0x10
#define ATARI_SCANCODE_W           0x11
#define ATARI_SCANCODE_E           0x12
#define ATARI_SCANCODE_R           0x13
#define ATARI_SCANCODE_T           0x14
#define ATARI_SCANCODE_Y           0x15
#define ATARI_SCANCODE_U           0x16
#define ATARI_SCANCODE_I           0x17
#define ATARI_SCANCODE_O           0x18
#define ATARI_SCANCODE_P           0x19
#define ATARI_SCANCODE_LBRACKET    0x1a
#define ATARI_SCANCODE_RBRACKET    0x1b
#define ATARI_SCANCODE_RETURN      0x1c
#define ATARI_SCANCODE_CTRL        0x1d
#define ATARI_SCANCODE_A           0x1e
#define ATARI_SCANCODE_S           0x1f
#define ATARI_SCANCODE_D           0x20
#define ATARI_SCANCODE_F           0x21
#define ATARI_SCANCODE_G           0x22
#define ATARI_SCANCODE_H           0x23
#define ATARI_SCANCODE_J           0x24
#define ATARI_SCANCODE_K           0x25
#define ATARI_SCANCODE_L           0x26
#define ATARI_SCANCODE_SEMICOLON   0x27
#define ATARI_SCANCODE_APOSTROPHE  0x28
#define ATARI_SCANCODE_GRAVE       0x29
#define ATARI_SCANCODE_LSHIFT      0x2a
#define ATARI_SCANCODE_BACKSLASH   0x2b
#define ATARI_SCANCODE_Z           0x2c
#define ATARI_SCANCODE_X           0x2d
#define ATARI_SCANCODE_C           0x2e
#define ATARI_SCANCODE_V           0x2f
#define ATARI_SCANCODE_B           0x30
#define ATARI_SCANCODE_N           0x31
#define ATARI_SCANCODE_M           0x32
#define ATARI_SCANCODE_COMMA       0x33
#define ATARI_SCANCODE_PERIOD      0x34
#define ATARI_SCANCODE_SLASH       0x35
#define ATARI_SCANCODE_RSHIFT      0x36
#define ATARI_SCANCODE_ALT         0x38
#define ATARI_SCANCODE_SPACE       0x39
#define ATARI_SCANCODE_CAPSLOCK    0x3a
#define ATARI_SCANCODE_F1          0x3b
#define ATARI_SCANCODE_F2          0x3c
#define ATARI_SCANCODE_F3          0x3d
#define ATARI_SCANCODE_F4          0x3e
#define ATARI_SCANCODE_F5          0x3f
#define ATARI_SCANCODE_F6          0x40
#define ATARI_SCANCODE_F7          0x41
#define ATARI_SCANCODE_F8          0x42
#define ATARI_SCANCODE_F9          0x43
#define ATARI_SCANCODE_F10         0x44
#define ATARI_SCANCODE_HOME        0x47
#define ATARI_SCANCODE_UP          0x48
#define ATARI_SCANCODE_LEFT        0x4b
#define ATARI_SCANCODE_RIGHT       0x4d
#define ATARI_SCANCODE_DOWN        0x50
#define ATARI_SCANCODE_INSERT      0x52
#define ATARI_SCANCODE_DELETE      0x53
#define ATARI_SCANCODE_HELP        0x62
#define ATARI_SCANCODE_UNDO        0x61

#endif
